### ISSUE TITLE
sleep dead

### ISSUE THREAD

**Issue by AXFULL** [Jeffery-Song/OpenCore-MSI-B460M-Mortar-10400#1]
Will sleep dead USB can't wake up
Ethernet is ok

**Comment by AXFULL** [comment]
OC 0.7.6

**Comment by molamooo** [comment]
What does "Will sleep dead USB can't wake up" mean?😂你可以说中文。
你说的sleep不是指关闭屏幕而是指睡眠是吗？这个功能我还没折腾，我目前只允许关闭显示器

**Comment by molamooo** [comment]
I've encountered similar issue when using iGPU under 11.6.1, opencore 0.7.5. Restart the monitor solves the issue.
Now I've switched to dGPU under 12.1, opencore 0.7.6, and usb wake up is working fine.
